# Generated by Django 4.0.4 on 2022-05-15 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_data2_alter_data_options_alter_data_humidity_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data2',
            new_name='DataB',
        ),
    ]
